### ISSUE TITLE
testing webhooks

### ISSUE THREAD

**Issue by fargozhu** [fargozhu/elixir_senml#28]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fargozhu** [comment]
adding comment

**Comment by sblabreu** [comment]
Funciona
Estás a prepara a lib para hex.pm?

**Comment by fargozhu** [comment]
@sblabreu vais precisar da lib? se sim eu posso fazer um refactoring...
